/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:19cd1051-6f84-49f7-ac49-694d78bbf820",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_SrdQGHOjt",
    "aws_user_pools_web_client_id": "8q3ijtli3jhk16jug0pfhonbi",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://h47uq2ds2jfmhfy25o3pnbc4nq.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-eldn4mupqnhi7bs6ep2nzytfe4",
    "aws_user_files_s3_bucket": "digiapp-bucket120954-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
