/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:19cd1051-6f84-49f7-ac49-694d78bbf820",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_SrdQGHOjt",
    "aws_user_pools_web_client_id": "8q3ijtli3jhk16jug0pfhonbi",
    "oauth": {}
};


export default awsmobile;
